blank_issues_enabled: true
contact_links:
    - name: Doctrine Extensions issues
      url: https://github.com/Dukecity/DoctrineExtensionsBundle/issues
      about: Issues about the extensions should be reported upstream.
